site_name: TODOLIST Docs
nav:
  - Home: index.md
  - Run: run.md
  - Arquitetura: architecture.md
  - Práticas e Padrões: practices.md
docs_dir: docs
site_dir: site
theme:
  name: material
plugins: []
